
"use client";

import React from "react";
import { format } from "date-fns";
import { Table, TableBody, TableCell, TableRow, TableHead, TableHeader } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import type { RotaGeneration, Shift, TeamMember } from "@/lib/types";
import { useRotaStore } from "@/lib/store";

type AdhocStatus = Record<string, Record<number, boolean>>;
type AdhocNotes = Record<string, string>;

interface SupportRotaExportImageProps {
    activeGeneration: RotaGeneration;
    teamMembersInRota: TeamMember[];
    weeks: { start: Date; end: Date }[];
    adhocStatus: AdhocStatus;
    adhocNotes: AdhocNotes;
}

export const SupportRotaExportImage = React.forwardRef<HTMLDivElement, SupportRotaExportImageProps>(
    ({ activeGeneration, teamMembersInRota, weeks, adhocStatus, adhocNotes }, ref) => {
        const { shifts } = useRotaStore();
        const shiftMap = new Map(shifts.map(s => [s.id, s]));
        const title = `Ad-Hoc Support Rota: ${format(weeks[0].start, 'd MMM')} - ${format(weeks[weeks.length - 1].end, 'd MMM yyyy')}`;

        return (
            <div ref={ref} className="p-8 bg-white text-black font-body w-[1200px]">
                <h2 className="text-2xl font-bold text-center mb-6">{title}</h2>
                <div className="border rounded-lg">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead className="font-semibold text-black">Team Member</TableHead>
                                <TableHead className="font-semibold text-black">Main Shift</TableHead>
                                {weeks.map((week, index) => (
                                    <TableHead key={index} className="font-semibold text-black text-center">
                                        Week {index + 1} ({format(week.start, 'd MMM')})
                                    </TableHead>
                                ))}
                                <TableHead className="font-semibold text-black">Adhoc Notes</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {teamMembersInRota.map(member => {
                                const shiftId = activeGeneration.assignments[member.id];
                                const shift = shiftId ? shiftMap.get(shiftId) : null;
                                return (
                                    <TableRow key={member.id}>
                                        <TableCell className="font-medium text-black">{member.name}</TableCell>
                                        <TableCell>
                                            {shift ? (
                                                <Badge
                                                    variant="secondary"
                                                    className="bg-gray-200 text-black"
                                                >
                                                    {shift.name}
                                                </Badge>
                                            ) : (
                                                <Badge variant="outline">Off</Badge>
                                            )}
                                        </TableCell>
                                        {weeks.map((_, index) => (
                                            <TableCell key={index} className="text-center text-black">
                                                {adhocStatus[member.id]?.[index] ? '✔️' : ''}
                                            </TableCell>
                                        ))}
                                        <TableCell className="text-xs text-gray-700">
                                            {adhocNotes[member.id] || ""}
                                        </TableCell>
                                    </TableRow>
                                );
                            })}
                        </TableBody>
                    </Table>
                </div>
                 <p className="text-xs text-gray-500 mt-4 text-center">Generated by RotaPro on {format(new Date(), 'PPpp')}</p>
            </div>
        );
    }
);

SupportRotaExportImage.displayName = 'SupportRotaExportImage';

